### ISSUE TITLE
Autosave makes empty files

### ISSUE THREAD

**Issue by iv230** [Infiziert90/XIVLogger#2]
It appears to me that several times, a file is left empty by the plugin while disconnected, using the autos aver. It is saved to write down every 5 minutes, so I could understand that few minutes are lost. But sometimes, and more and more often files are left empty, while disconnecting, not closing the game. My folder of logs starts to be huge and containing a lot of them (using it since several months), I don't know if this can be an issue. A tried to look out for logs un Dalamud but nothing is printed.
I attached my config.

[XIVLogger.json](https://github.com/Infiziert90/XIVLogger/files/13210891/XIVLogger.json)

**Comment by Infiziert90** [comment]
Autosave will create a file for each of your character, everytime you start your game / log to a different char
So yes the log folder will quickly increase in number of files, that was always the intention just that it was bugged pre update

I will look into what the issue could be
Just to get the question out, in the times you see an empty file, are there any messages in your chat that should have been saved?

**Comment by 264-bit** [comment]
I'm seeing this too.  Empty autosaved log files when I expect messages in the log.  It works if I manually save the log from the plugin's interface.
I did enable autosave notifications and I see the notifications, just nothing in the filename it prints.

**Comment by iv230** [comment]
I can confirm that I sould have logs in those files.

@264-bit how to peroperly run the manual save, so that it ends up in the autosave file?

**Comment by iv230** [comment]
@Infiziert90 It seems that the issue appears on character login. A file is created and left empty, even if the auto-saver is supposed to be running. It does not look like an accidental deletion after logging out.
Hitting the save log button will save the actual log in a file that does not contain the character name in its name.

I'm also using Snooper, another plugin that interacts with the logs (being able to see in a window only the log of your current target); can it create a conflict?

**Comment by Infiziert90** [comment]
If there is still issues after this update, please write a comment here
