### ISSUE TITLE
Saving /random rolls only logs my own

### ISSUE THREAD

**Issue by digiAlchem** [Infiziert90/XIVLogger#3]
I've noticed that the plugin is only saving "Random!" rolls that I have made, and not anybody else's.

I can't spot an individual setting for it, and it doesn't seem to matter whether the person rolling is in a party with me or not — I don't know if that would even make a difference!

(Thank you for this amazing plugin, it's been an absolute lifesaver for re-reading RP scenes 💜)

**Comment by Infiziert90** [comment]
Random rolls use a different chat type depending on if they come from you or another person
Can look into adding them to the nornal "random" category

(also didn't wanna close)

**Comment by digiAlchem** [comment]
That sounds like something this game would do 😂 Thank you so much!

**Comment by Infiziert90** [comment]
Implemented in the latest update
