### ISSUE TITLE
[Request] Log by Chat Type

### ISSUE THREAD

**Issue by NatAvo** [Infiziert90/XIVLogger#7]
Save file by chat type.

Separate out log files by chat type IE

Party_20240827.txt
Tell_20240827.txt
Alliance_20240827.txt
FC_20240827.txt
etc.

This would make it a lot easier to find things when there are multiple conversations happening all at once and mixed within the output log file.

**Comment by Infiziert90** [comment]
Not planned for now, if you want a more in-depth logging it would be best to use either ChatTwo with its /chat2Viewer or Chatter
