### ISSUE TITLE
Minutes to seconds ?

### ISSUE THREAD

**Issue by Tashiro64** [Infiziert90/XIVLogger#8]
Hi! First of all, I wanted to tell you that your plugin is very useful to me, it helped me create some great stuff for my FC. The only "problem" I have is the limitation of "Every 1 minute", for what i'm using it, a minute is a bit long, would it be hard for you to swap the minutes into seconds ? So chatlog could be saved every 5 seconds if I want to.

Dont know if it has anything to do with AddMinutes in checktime(), but yeah, this would be so freaking nice if it was possible, i'm sure some other people would love that too!

Keep me updated on this :)

**Comment by Infiziert90** [comment]
This is not really planned. 

Your use case sounds more of one that should directly interact with chat through a plugin, instead of using one that saves to disk first :)
